name: Linters

on: pull_request

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '>=3.1.x'
      - name: Setup Rubocop
        run: |
          gem install --no-document rubocop:"~> 1.0" # Install rubocop gem with version requirement '~> 1.0'gem install --no-document rubocop:"< 2.0" [ -f .rubocop.yml ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/ruby/.rubocop.yml # Download .rubocop.yml configuration file

      - name: Rubocop Report
        run: rubocop --color
